kind: Deployment
metadata:
  name:  image-server
  labels:
    app:  image-server
spec:
  selector:
    matchLabels:
      app: image-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  image-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  image-server
        image: nginx:1.27.2-alpine
        resources:
          requests:
            cpu: 1000m
            memory: 10Mi
        ports:
        - containerPort:  80
          name:  image-server
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: image-server-claim
      restartPolicy: Always
