apiVersion: v1
kind: Service
metadata:
  name: image-server
spec:
  selector:
    app: image-server
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: image-server
    protocol: TCP
    port: 8080
    targetPort: 80
