apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: <CLUSTER_NAME>
  namespace: <NAMESPACE>
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.22.0.0/22
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: <CLUSTER_CONTROLPLANE_REFERENCE_NAME>
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: <METAL3_CLUSTER_NAME_REFERENCE>
